export const DEVELOPERS_LIST_REQUEST = 'DEVELOPERS_LIST_REQUEST'
export const DEVELOPERS_LIST_SUCCESS = 'DEVELOPERS_LIST_SUCCESS'
export const DEVELOPERS_LIST_FAIL = 'DEVELOPERS_LIST_FAIL'

export const DEVELOPERS_DETAILS_REQUEST = 'DEVELOPERS_DETAILS_REQUEST'
export const DEVELOPERS_DETAILS_SUCCESS = 'DEVELOPERS_DETAILS_SUCCESS'
export const DEVELOPERS_DETAILS_FAIL = 'DEVELOPERS_DETAILS_FAIL'

export const DEVELOPER_LOGIN_REQUEST = 'DEVELOPER_LOGIN_REQUEST'
export const DEVELOPER_LOGIN_SUCCESS = 'DEVELOPER_LOGIN_SUCCESS'
export const DEVELOPER_LOGIN_FAIL = 'DEVELOPER_LOGIN_FAIL'

export const DEVELOPER_REGISTER_REQUEST = 'DEVELOPER_REGISTER_REQUEST'
export const DEVELOPER_REGISTER_SUCCESS = 'DEVELOPER_REGISTER_SUCCESS'
export const DEVELOPER_REGISTER_FAIL = 'DEVELOPER_REGISTER_FAIL'

export const DEVELOPER_EDIT_REQUEST = 'DEVELOPER_EDIT_REQUEST'
export const DEVELOPER_EDIT_SUCCESS = 'DEVELOPER_EDIT_SUCCESS'
export const DEVELOPER_EDIT_FAIL = 'DEVELOPER_EDIT_FAIL'

export const DEVELOPER_ADD_SKILL_REQUEST = 'DEVELOPER_ADD_SKILL_REQUEST'
export const DEVELOPER_ADD_SKILL_SUCCESS = 'DEVELOPER_ADD_SKILL_SUCCESS'
export const DEVELOPER_ADD_SKILL_FAIL = 'DEVELOPER_ADD_SKILL_FAIL'

export const DEVELOPER_ADD_PROJECT_REQUEST = 'DEVELOPER_ADD_PROJECT_REQUEST'
export const DEVELOPER_ADD_PROJECT_SUCCESS = 'DEVELOPER_ADD_PROJECT_SUCCESS'
export const DEVELOPER_ADD_PROJECT_FAIL = 'DEVELOPER_ADD_PROJECT_FAIL'

export const DEVELOPER_EDIT_SKILL_REQUEST = 'DEVELOPER_EDIT_SKILL_REQUEST'
export const DEVELOPER_EDIT_SKILL_SUCCESS = 'DEVELOPER_EDIT_SKILL_SUCCESS'
export const DEVELOPER_EDIT_SKILL_FAIL = 'DEVELOPER_EDIT_SKILL_FAIL'

export const DEVELOPER_DELETE_SKILL_REQUEST = 'DEVELOPER_DELETE_SKILL_REQUEST'
export const DEVELOPER_DELETE_SKILL_SUCCESS = 'DEVELOPER_DELETE_SKILL_SUCCESS'
export const DEVELOPER_DELETE_SKILL_FAIL = 'DEVELOPER_DELETE_SKILL_FAIL'

export const DEVELOPER_DELETE_PROJECT_REQUEST = 'DEVELOPER_DELETE_PROJECT_REQUEST'
export const DEVELOPER_DELETE_PROJECT_SUCCESS = 'DEVELOPER_DELETE_PROJECT_SUCCESS'
export const DEVELOPER_DELETE_PROJECT_FAIL = 'DEVELOPER_DELETE_PROJECT_FAIL'