export const DEVELOPERS_LIST_REQUEST = 'DEVELOPERS_LIST_REQUEST'
export const DEVELOPERS_LIST_SUCCESS = 'DEVELOPERS_LIST_SUCCESS'
export const DEVELOPERS_LIST_FAIL = 'DEVELOPERS_LIST_FAIL'

export const DEVELOPERS_DETAILS_REQUEST = 'DEVELOPERS_DETAILS_REQUEST'
export const DEVELOPERS_DETAILS_SUCCESS = 'DEVELOPERS_DETAILS_SUCCESS'
export const DEVELOPERS_DETAILS_FAIL = 'DEVELOPERS_DETAILS_FAIL'